### PR TITLE
Fix wrong cased import of the MultiTab component.

### PR DESCRIPTION
**Pull request by iceteabottle**
Bildschirmfoto 2019-10-16 um 14 54 28

@rhtyd that fixes the master build ;)

### CODE REVIEW

**Comment by rhtyd** [comment]
Thanks @iceteabottle, can you check latest master which has https://github.com/shapeblue/primate/tree/master/src/components/multitab

**Comment by iceteabottle** [comment]
> I've renamed the directory on master
That's why we need to adjust the import.

**Comment by rhtyd** [comment]
@iceteabottle yes, but the name of the director is lowered case now than 'components/multitab'. Let me test your fix, sorry if I misunderstood.

**Comment by rhtyd** [comment]
@iceteabottle I'm unable to reproduce the issue, the folder path is `src/components/multitab` I don't think we need to rever that. Can you stop your npm service, and do: npm install and try again?

**Comment by iceteabottle** [comment]
@rhtyd Are you developing on windows?

**Comment by rhtyd** [comment]
@iceteabottle I'm on GNU/Linux (Ubuntu 19.04); can you try delete node_modules, try npm install and launch again (npm run serve)?

**Comment by iceteabottle** [comment]
That will not help because the multi tab component is an external dependency.

Bildschirmfoto 2019-10-16 um 15 35 19

**Comment by iceteabottle** [comment]
In which commit you renamed the directory?

**Comment by rhtyd** [comment]
@iceteabottle Can you pull --rebase latest master. See:
https://github.com/shapeblue/primate/tree/master/src/components/multitab
https://github.com/shapeblue/primate/commit/f15c558c265feb284f8d502fa399d912a2198dbc

**Comment by iceteabottle** [comment]
Ok, I see... Strange. I can see the change in the git history but it's wrong cased on my machine.
Bildschirmfoto 2019-10-16 um 15 38 42

**Comment by rhtyd** [comment]
Cool, kindly update the repo (git fetch origin master) on your local machine to fix and close the PR on your confirmation. Thanks @iceteabottle

**Pull request closed without merging**
